Remove obsolete u"" literal
The u"" literal triggers an internal error with black 19.3b0. While strictly
unrelated to this feature branch, we fix it here because the internal error only
reproduces on this branch.

  ❯ nox -s lint

  nox > Running session lint
  nox > Creating virtual environment (virtualenv) using python3.8 in .nox/lint
  nox > python -m pip install flake8==3.7.8 black==19.3b0 isort==4.3.21 mypy==0.720
  nox > mypy --disallow-untyped-defs --warn-unused-ignores --ignore-missing-imports nox
  nox > black --check nox tests noxfile.py setup.py
  error: cannot format …/nox/tests/test_command.py: INTERNAL ERROR: Black
  produced code that is not equivalent to the source. Please report a bug on
  https://github.com/ambv/black/issues. This diff might be helpful: /tmp/blk_d4e49p90.log
  All done! 💥 💔 💥
  38 files would be left unchanged, 1 file would fail to reformat.
  nox > Command black --check nox tests noxfile.py setup.py failed with exit code 123
  nox > Session lint failed.

  ❯ cat /tmp/blk_d4e49p90.log

  --- src
  +++ dst
  @@ -2092,18 +2092,18 @@
                    value=
                      Dict(
                        keys=
                          Constant(
                            kind=
  -                            'u',  # str
  +                            None,  # NoneType
                            value=
                              'SIGIL',  # str
                          )  # /Constant
                        values=
                          Constant(
                            kind=
  -                            'u',  # str
  +                            None,  # NoneType
                            value=
                              '123',  # str
                          )  # /Constant
                      )  # /Dict
                  )  # /keyword