Avoid mypy warning due to incompatible types in assignment
  nox/popen.py:77:
  error: Incompatible types in assignment
  (expression has type "Optional[bytes]", variable has type "bytes")